config/routes.rb
Redarmy::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :topics, :only => [:create, :destroy]
  resources :posts, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  
  root :to => 'pages#home'

end

app/models/post.rb
# == Schema Information
# Schema version: 20110421081320
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  content    :text
#  user_id    :integer
#  topic_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  attr_accessible :content
  
  belongs_to :topic
  belongs_to :user
  
  validates :content, :presence => true
  validates :user_id, :presence => true
  validates :topic_id, :presence => true
  
  default_scope :order => 'posts.created_at DESC'
end

app/models/topic.rb
# == Schema Information
# Schema version: 20110421081320
#
# Table name: topics
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Topic < ActiveRecord::Base
  attr_accessible :title
  
  belongs_to :user
  has_many :posts
  
  def topiclist
    Topic.all
  end
  
  default_scope :order => 'topics.created_at DESC'
end

app/models/user.rb
# == Schema Information
# Schema version: 20110421081320
#
# Table name: users
#
#  id                 :integer         primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :timestamp
#  updated_at         :timestamp
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :topics
  has_many :posts
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true
  validates :email, :presence => true, :format => {:with => email_regex}
  validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  #return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      @topic = Topic.new
      @topiclist = Topic.all
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password up in this bitch"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate
  
  def create
    @topic = current_user.topics.build(params[:topic])
    if @topic.save
      flash[:success] = "Topic created"
      redirect_to root_path
    else
      @topiclist = []
      render 'pages/home'
    end
  end
  
  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Enlist"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to redarmy.es!"
      redirect_to @user
    else
      @title = "Enlist"
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @title = "Edit User"
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def index
    @title = "All users"
    # @users = User.paginate(:page => params[:page])
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
    @topiclist = @user.topics.all
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis
  def title
    base_title = "redarmy.es"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  private
    
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    def store_location
      session[:return_to] = request.fullpath
    end
    
    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name, :class => 'gravatar', :gravatar => options)
  end
end

app/views/layouts/_footer.html.haml
%footer
	%nav.round
		%ul
			%li
				= link_to "About", about_path
			%li
				= link_to "Contact", contact_path
			%li
				%a{:href => "http://belgianman.com"}
					Belgian Man Records

app/views/layouts/_header.html.haml
%header
	%h1
		= link_to "redarmy.es", root_path
	%nav.round
		%ul
			%li
				= link_to "Home", root_path
			- if signed_in?
				%li
					= link_to "Users", users_path
				%li
					= link_to "Profile", current_user
				%li
					= link_to "Settings", edit_user_path(current_user)
				%li
					= link_to "Sign out", signout_path, :method => :delete
			- else
				= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print.css', :media=> 'print'
/[if lt IE 8]
	= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/custom.css', :media => 'screen'
= stylesheet_link_tag :all

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title
			= @title
		%link{:rel => "shortcut icon", :href => "/favicon.ico"}
		= csrf_meta_tag
		= render 'layouts/stylesheets'
		= javascript_include_tag :defaults
	%body
		.container
			= render 'layouts/header'
			%section.round
				- flash.each do |key, value|
					= content_tag(:div, value, :class => "flash #{key}")
				%h1
					= @title
				= yield
			= render 'layouts/footer'

app/views/pages/about.html.haml
%p
	redarmy.es private forum.

app/views/pages/contact.html.haml
%p
	you can reach me at
	%a{:href=>"mailto:ajm@andrewmonks.net"}
		ajm@andrewmonks.net

app/views/pages/home.html.haml
- if signed_in?
	%table.front{:summary => "For signed-in users"}
		%tr
			%td.main
				%h1.topic
					Create a topic:
				= render 'shared/topic_form'
				- unless @topiclist.empty?
					= render @topiclist
			%td.sidebar.round
				= render 'shared/user_info'
		/ %tr
		/ 	%ul.topics
		/ 		= render @topics
- else
	= link_to "Enlist!", signup_path, :class=> "signup_button round"

app/views/shared/_error_messages.html.haml
= if object.errors.any?
	#error_explanation
		%h2
			= pluralize(object.errors.count, "error")
			prohibited this
			= object.class.to_s.underscore.humanize.downcase
			from being saved:
		%p
			There were problems with the following fields:
		%ul
			= object.errors.full_messages.each do |msg|
				%li
					= msg

app/views/shared/_topic.html.haml
%tr
	%td.topic
		%span.user
			= link_to topic.user.name, topic.user
		%span.title
			= topic.title
		%span.timestamp
			Posted
			= time_ago_in_words(topic.created_at)
			ago

app/views/shared/_topic_form.html.haml
= form_for @topic do |f|
	= render 'shared/error_messages', :object => f.object
	.field
		= f.text_field :title
	.actions
		= f.submit "Submit"

app/views/shared/_topiclist.html.haml
- unless @topiclist.empty?
	%table.topiclist
		=render :partial => 'shared/topic', :collection => @topics

app/views/shared/_user_info.html.haml
.user_info
	%a{:href =>"#{user_path(current_user)}"}
		= gravatar_for current_user, :size => 30
		%span.user_name
			= current_user.name
		%span.topics
			=pluralize(current_user.topics.count, "topic")

app/views/topics/_topic.html.haml
%tr
	%td.topic
		%span.title
			= topic.title
		%span.timestamp
			Created
			= time_ago_in_words(topic.created_at)
			ago

app/views/users/_fields.html.haml
= render 'shared/error_messages', :object => f.object
.field
	= f.label :name, "Full name"
	%br
	= f.text_field :name
.field
	= f.label :email
	%br
	= f.text_field :email
.field
	= f.label :password
	%br
	= f.password_field :password
.field
	= f.label :password_confirmation, "Password confirmation"
	%br
	= f.password_field :password_confirmation

app/views/users/_user.html.haml
%li
	= gravatar_for user, :size => 30
	= link_to user.name, user
	- if current_user.admin?
		= link_to "delete", user, :method=> :delete, :confirm => "You sure?", :title => "Delete #{user.name}"

app/views/users/edit.html.haml
= form_for(@user) do |f|
	= render 'fields', :f => f
	.actions
		= f.submit "Update"
%div
	= gravatar_for @user
	%a{:href => "http://gravatar.com/emails"}
		change

app/views/users/index.html.haml
/ = will_paginate
%ul.users
	= render @users
/ = will_paginate

app/views/users/new.html.haml
= form_for(@user) do |f|
	= render 'fields', :f => f
	.actions
		= f.submit "Enlist"

app/views/users/show.html.haml
%table.profile{:summary => "Profile information"}
	%tr
		%td.main
			= gravatar_for @user
			- unless @user.topics.empty?
				%table.topics
					= render @topiclist
		%td.sidebar.round
			%strong
				Name
			=@user.name
			%br
			%strong
				URL
			= link_to user_path(@user), @user
			%br
			%strong
				email
			= @user.email
			%br
			%strong
				Topics
			= @user.topics.count